name: Chocolatine Workflow

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  check_coding_style:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Coding Style Checker
        run: check.sh $(pwd) $(pwd)

  check_program_compilation:
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Make
        run: make
        timeout-minutes: 2

      - name: Run Make Clean
        run: make clean

      - name: Verify Executables
        run: |
          for executable in $(echo $EXECUTABLES | tr ',' ' '); do
            if [ ! -x "$executable" ]; then
              echo "Error: $executable is either missing or not executable."
              exit 1
            fi
          done
        env:
          EXECUTABLES: ${{ secrets.EXECUTABLES }}

  run_tests:
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Run Tests
        run: make tests_run
        timeout-minutes: 2

  push_to_mirror:
    runs-on: ubuntu-latest
    needs: [check_coding_style, check_program_compilation, run_tests]
    if: "!startsWith(github.ref, 'refs/heads/ga-ignore-') && github.event_name == 'push'"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - run: echo ${{ secrets.MIRROR_URL }}
      
      - name: Push to Mirror
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ secrets.MIRROR_URL }}
          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}

defaults:
  run:
    shell: bash
    working-directory: .
